### PR TITLE
Clang3.4 port

### PR DESCRIPTION
**Pull request by eras**
Ported to compile and pass tests with Clang3.4 (except for the remove-variables.cl which didn't work for me in the first place).

Also includes a fix to issue #69 as the last change.

### CODE REVIEW

**Comment by elhigu** [comment]
Code looks great. Did seem to work fine on OSX too. One test failed with pocl driver, but that is not a blocker for merge.

**Comment by wolfviking0** [comment]
Hi, I just update the version of validator for 3.4, everything seems working, but just in case, the modification to do inside clang are just adding the webcl-validator subdirectory inside the CMakeList ??

**Comment by tbrutch** [comment]
Thanks

**Comment by elhigu** [comment]
We still need to update readme.md file with updated instructions. Anthony is right that there is a little addition needed to be done to `CMakeLists.txt` in `clang/tools` directory. 

To compile validator with llvm/clang 3.4 one needs to first checkout webcl-validator master to llvm source directory `llvm-3.4/tools/clang/tools/webcl-validator` and add `add_subdirectory(webcl-validator)` line to `llvm-3.4/tools/clang/tools/CMakeLists.txt`.

**Pull request merged**
